### ISSUE TITLE
Window size

### ISSUE THREAD

**Issue by stephanie121** [kpreisser/MouseClickSimulator#20]
Hi,
The program is amazing and I used it today, and it worked fine. Then I completely logged out (and closed completely) and logged back on to another account. I went to the exact same place for fishing, using the same program, but it said something about window ratio. I never adjusted window ratio, it was default for the first account and the second. Please help?

**Comment by kpreisser** [comment]
Hi,

the message about the window ratio should only occur when the Toontown window width is smaller than the window height * 4 / 3. When using default resolutions in windowed mode (800x600, 1024x768) or maximizing the window to full screen, this message shouldn't occur.
Can you post a screenshot of your TT window when this error occurs?

**Comment by stephanie121** [comment]
![issue](https://cloud.githubusercontent.com/assets/28494833/26563488/5daf1bc6-4498-11e7-9ec1-a8d3cfefd45d.JPG)

**Comment by stephanie121** [comment]
![issue](https://cloud.githubusercontent.com/assets/28494833/26563501/96cc9d98-4498-11e7-8c5f-faa2cee2cdfc.JPG)

**Comment by stephanie121** [comment]
It only occurs when performing the sample actions.

**Comment by kpreisser** [comment]
Hi,
from looking at the screenshot (which I received via eMail), I can see that your TT window has an inner size of 999x750. This would explain the error message, as the simulator would require the width to be at least 1000 instead of 999. I think you have set a 125% scaling for your screen in the Windows Display Settings, and set TT Rewritten to a size of 800x600, which is then scaled to about 1000x750 (but the 999 could result from a rounding error).

When you increase the width of the TT Rewritten window, the error should not occur any more. (I think TT Rewritten needs to fix `TTREngine.exe`'s application manifest to include a `<dpiAware .../>` setting in order to mark the application as high DPI aware, which should fix the pixelize looking of TT Rewritten for higher screen scalings).
