### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by bryan8307** [kpreisser/MouseClickSimulator#34]
hi,  I have installed Microsoft Build Tools 2015 Update 3 and Microsoft .NET Framework 4.6 targeting packet.  When running the build, an error states:

C:\program files (x86)\MSbuild\14.0\bin\Microsfot.common.CurrentVersion.targets(1098,5):error MSB3644:  The reference assemblies for framework ".NETFramework,Version=v4.6" were not found.  To resolve this, install the SDK or targeting Pack for this framework version.    But based on installed apps, I do have the targeting pack installed.  

How do I resolve this?

**Comment by malikis2cool** [comment]
There's two 4.6 package options to download. Make sure you download the correct one. It didn't work for me until I downloaded it correctly. 


NDP46-TargetingPack-KB3045566.exe --- correct one

NDP46-TargetingPack-KB3045566-ENU.exe --- this is incorrect

**Comment by kpreisser** [comment]
Thanks for creating this issue (and sorry for not replying earlier).
The advice given by @Milbes was correct, the download page showed a list of files where you needed to select the right one.

Since the recent updates, the simulator now uses .NET 8.0, so this should no longer be relevant as now the .NET SDK is required instead of the .NET Framework targeting pack.
