### ISSUE TITLE
Fishing

### ISSUE THREAD

**Issue by Phrimzy** [kpreisser/MouseClickSimulator#4]
Hello, I am trying to use the automatic fisher for TTR. Everything is working accept when I try to cast, It just says searching for the fish bubbles... I have restarted and re downloaded many times but I can't figure it out, please help! I really want this to work.

**Comment by TTExtensions** [comment]
Hi,
unfortunately, the fishing function currently doesn't work for TT Rewritten because of the Winter Holiday theme which is currently used. It changed the colors to be a bit darker, so the simulator currently cannot find the fishing bubbles. Once the event is over, the fishing function should work again.

However, in order to make the simulator work on such events the fishing function should be rewritten to not search for specific colors, but instead for each scan point scan the area around it and check if the center is darker than the outer region.

When I can find some time I will start working on this (or if someone else can work on this, he/she can submit a pull request).
Thanks

**Comment by Phrimzy** [comment]
Thank you for clearing that up. I was concerned.

**Comment by TTExtensions** [comment]
Hi,

as a workaround until the fishing function has been rewritten, I have included a new project file for automatic fishing in Punchline Place during the Winter Holidays (Filename: "Automatic Fishing - Punchline Place (Winter Holidays).xml").

**Comment by Phrimzy** [comment]
Sweet I'll look at it when I get home, Thanks!
